jitemizer:
  persistence:
    manager: mongo

spring:
  main:
    show-banner: false
  application:
    name: jitemizer
    
server:
  #port: 8080
  #contextPath: /
  ssl:
    key-store: file:///path/to/mykeys.jks
    key-store-password: letmein
    key-password: letmein
    
management.security.enabled: false

security:
    oauth2.resource.userInfoUri: http://localhost:8080/api/auth/user
    #user.password: password
    basic.enabled: false

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
        
# enabling h2 webcosole
# http://localhost:8080/h2-console
spring.h2.console.enabled: true
# spring.jpa.hibernate.ddl-auto=create

#spring:
#  datasource:
    # url: jdbc:mysql://localhost:3306/jitemizer
    # username: dbuser
    # password: dbpass
